// This file is autogenerated by the AI. Do not edit this file directly.
import data from './placeholder-images.json';

// Simple image placeholder
type ImagePlaceholder = {
  id: string;
  description: string;
  imageUrl: string;
  imageHint: string;
};

// For collections of images, like testimonials or carousels
type ImageCollection = {
  id: string;
  description: string;
  images: { image: string; hint: string }[];
};

type CommunityCreations = {
  id: string;
  description: string;
  creations: { image: string; hint: string; user: string }[];
}

export const placeholderImages = {
  heroGourmetDinner: data.placeholderImages.find(p => p.id === 'hero-gourmet-dinner') as ImagePlaceholder,
  platformMockup: data.placeholderImages.find(p => p.id === 'platform-mockup') as ImagePlaceholder,
  premiumGreenDrink: data.placeholderImages.find(p => p.id === 'premium-green-drink') as ImagePlaceholder,
  finalCtaBackground: data.placeholderImages.find(p => p.id === 'final-cta-background') as ImagePlaceholder,
  aiChefMockup: data.placeholderImages.find(p => p.id === 'ai-chef-mockup') as ImagePlaceholder,
  
  // Benefits
  benefitRecipes: data.placeholderImages.find(p => p.id === 'benefit-recipes') as ImagePlaceholder,
  benefitDrinks: data.placeholderImages.find(p => p.id === 'benefit-drinks') as ImagePlaceholder,
  benefitSnacks: data.placeholderImages.find(p => p.id === 'benefit-snacks') as ImagePlaceholder,
  benefitInfusion: data.placeholderImages.find(p => p.id === 'benefit-infusion') as ImagePlaceholder,
  benefitMenus: data.placeholderImages.find(p => p.id === 'benefit-menus') as ImagePlaceholder,
  benefitAiTech: data.placeholderImages.find(p => p.id === 'benefit-ai-tech') as ImagePlaceholder,

  // Collections
  testimonials: data.placeholderImages.find(p => p.id === 'testimonials') as ImageCollection,
  portalPreviews: data.placeholderImages.find(p => p.id === 'portal-previews') as ImageCollection,
  communityCreations: data.placeholderImages.find(p => p.id === 'community-creations') as CommunityCreations,
};
