// This file is autogenerated by the AI. Do not edit this file directly.
import data from './placeholder-images.json';

// Simple image placeholder
type ImagePlaceholder = {
  id: string;
  description: string;
  imageUrl: string;
  imageHint: string;
};

// For collections of images, like testimonials or carousels
type ImageCollection = {
  id: string;
  description: string;
  images: { image: string; hint: string }[];
};

type CommunityCreations = {
  id: string;
  description: string;
  creations: { image: string; hint: string; user: string }[];
}

const placeholderData = data.placeholderImages as (ImagePlaceholder | ImageCollection | CommunityCreations)[];

function findImage<T extends ImagePlaceholder | ImageCollection | CommunityCreations>(id: string): T {
  const item = placeholderData.find(p => p.id === id);
  if (!item) {
    throw new Error(`Placeholder image with id "${id}" not found.`);
  }
  return item as T;
}

export const placeholderImages = {
  heroGourmetDinner: findImage<ImagePlaceholder>('hero-gourmet-dinner'),
  platformMockup: findImage<ImagePlaceholder>('platform-mockup'),
  premiumGreenDrink: findImage<ImagePlaceholder>('premium-green-drink'),
  finalCtaBackground: findImage<ImagePlaceholder>('final-cta-background'),
  aiChefMockup: findImage<ImagePlaceholder>('ai-chef-mockup'),
  
  // Benefits
  benefitRecipes: findImage<ImagePlaceholder>('benefit-recipes'),
  benefitDrinks: findImage<ImagePlaceholder>('benefit-drinks'),
  benefitSnacks: findImage<ImagePlaceholder>('benefit-snacks'),
  benefitInfusion: findImage<ImagePlaceholder>('benefit-infusion'),
  benefitMenus: findImage<ImagePlaceholder>('benefit-menus'),
  benefitAiTech: findImage<ImagePlaceholder>('benefit-ai-tech'),

  // Collections
  testimonials: findImage<ImageCollection>('testimonials'),
  portalPreviews: findImage<ImageCollection>('portal-previews'),
  communityCreations: findImage<CommunityCreations>('community-creations'),
};
